# This is a basic workflow to help you get started with Actions

name: Maven Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1
      - name: Checkout the main branch
        uses: actions/checkout@v3

      # Step 2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Step 3
      - name: Build the project
        run: mvn -B package --file course_work2.iml
      
      # Step 4
      - name: Upload Artefact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "*.exe"
          retention-days: 5
  
  telergam:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artefact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: my-artifact
      
      - name: failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            You failed
      
      - name: send mess
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: my-artifact/**
          message: |
            ${{ github.actor }} created commit № ${{ github.run_number }}:
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Download ${{ env.app_name }} Artifacts
